### ISSUE TITLE
PluginToAar - WindowsError 2

### ISSUE THREAD

**Issue by Deepscorn** [helpshift/dexter#5]
Running
C:\Python27>python PluginToAAR.py -p C:\Users\Venom\projects\playunity\Empty2018.1.9f1
produces WindowsError2

Environment:
Windows 10
Python 2.7.9 https://www.python.org/ftp/python/2.7.9/python-2.7.9.amd64.msi
Unity 2018.1.9f1

Steps to reproduce:

Create empty unity project

Then follow instructions: https://developers.helpshift.com/unity/getting-started-android/
Details:
1. import unitypackage (Helpshift SDK-only dex unity package v. 4.1.0) 
2. change ${applicationId} with <your app package> в Plugins/Android/helpshift/AndroidManifest.xml

3. run build - will get error
CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Java\jdk1.8.0_181\bin\java.exe -classpath "C:\Users\Venom\projects\supercity\.sdk\Unity-2018.1.9f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.0.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx2048m" "assembleRelease"

stderr[
warning: string 'status_bar_notification_info_overflow' has no default translation.

C:\Users\Venom\projects\playunity\Empty2018.1.9f1\Temp\gradleOut\design-26.0.2\build\intermediates\bundles\default\res\values\values.xml:238: AAPT: Error retrieving parent for item: No resource found that matches the given name 'Animation.AppCompat.Dialog'.
    
C:\Users\Venom\projects\playunity\Empty2018.1.9f1\Temp\gradleOut\design-26.0.2\build\intermediates\bundles\default\res\values\values.xml:256: AAPT: Error retrieving parent for item: No resource found that matches the given name 'TextAppearance.AppCompat.Display1'.

...

4. Perform workaround - use that script PluginToAAR.py (https://developers.helpshift.com/unity/troubleshooting-android/#fix-inbuilt-gradle-build)

a. remove dirs
b. put aars (downloaded from e.g. https://mvnrepository.com/artifact/com.android.support/support-vector-drawable/26.0.2)
c. download python 2.7.9 (it's bundled with pip)
d. run  pip install requests==2.7.0

d. run:
C:\Python27>python PluginToAAR.py -p C:\Users\Venom\projects\playunity\Empty2018.1.9f1
INFO:root:Checking for updates...
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): raw.githubusercontent.com
INFO:root:Creating backup of "C:\Users\Venom\projects\playunity\Empty2018.1.9f1\Assets\Plugins\Android\helpshift" at C:\Users\Venom\projects\playunity\Empty2018.1.9f1\helpshift_bkp
Traceback (most recent call last):
  File "PluginToAAR.py", line 109, in <module>
    sys.exit(main(args))
  File "PluginToAAR.py", line 92, in main
    aar_path = generate_aar(helpshift_aar_unzipped)
  File "PluginToAAR.py", line 41, in generate_aar
    call(["jar", "cvf", "Helpshift.aar","."])
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2]

**Comment by Deepscorn** [comment]
Project: https://www.dropbox.com/s/e4w403kdwc3oo36/Empty2018.1.9f1.zip?dl=0

**Comment by Mithraell** [comment]
I had the same issue.

What you can try is to actually test out first by typing into bash or cmd `jar` and if it is not found, you know that you either do not have the JDK installed or that your environment path doesn't contain the path to the `jar` file.

The file itself should be located in your JDK installation location.
The default installation location is `C:\Program Files\Java\{jdk_version}\bin`

**Comment by Deepscorn** [comment]
Fixed, thanks @Mithraell
